package com.dae.kdmes.DTO.App02;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
public class Index10Dto {
    private String custcd;
    private String spjangcd;
    private String plan_no;
    private String plan_new;
    private String pcode;
    private String wodv;
    private String ecltnm;
    private String wdndv;
    private String wrmc;
    private String wono;
    private String lotno;
    private String lotnomax;
    private String line;
    private String opcod;
    private String cltcd;
    private String wocs;
    private String wram;
    private String woam;
    private String prod_sdate;
    private String prod_edate;
    private Integer prod_qty;
    private String prod_dqty;
    private String qcdate;
    private String qcqty;
    private String end_qty;
    private String ordtype;
    private String orddate;
    private String ordnum;
    private String ordseq;
    private String ordqty;
    private String ord_edate;
    private String outtm;
    private String close_date;
    private String close_perid;
    private Integer decision;
    private Integer cls_flag;
    private String work_flag;
    private Integer dem_flag;
    private Integer rw_flag;
    private String qc_flag;
    private String close_flag;
    private String end_flag;
    private String istore;
    private String ostore;
    private String rwflag;
    private String perid;
    private String pernm;
    private String remark;
    private String workdv;
    private String wflag;
    private String wseq;
    private String tordqty;
    private String qcgb;
    private String demdate;
    private String demnum;
    private String selps;
    private String selck;
    private String batchdv;
    private String ocls_flag;
    private String autodv;
    private String fdate;
    private String tdate;
    private String indate;
    private String inperid;
    private String jpum;
    private String jgugek;
    private String jchajong;
    private String jsayang;
    private String jgugek2;
    private String jpumcode;
    private String jdanwy;
    private String j_sr;
    private String Jpb_gubn;
    private String Jmodel_code;

    private String acorp1;
    private String acorp2;
    private String acorp3;
    private String cifcodename;
    private String acorp;
    private String asano1;
    private String asano2;
    private String asano3;
    private String asanotxt;
    private String aname;
    private String aupte;
    private String ajong;
    private String apost1;
    private String ajuso1;
    private String ajuso2;
    private String abigo;
    private String agita;
    private String ajumi1;
    private String ajumi2;
    private String ajumitxt;
    private String aascode1;
    private String aascode2;
    private String aascodetxt;
    private String atelno;
    private String atelno2;
    private String ahand;
    private String aemail;
    private String abonsadam1;
    private String abonsadam2;
    private String abonsadam3;
    private String inname01;
    private String inname02;
    private String inname03;
    private String adomain;
    private String afax;
    private String acode;
    private String ajusotxt;
    private String inname;
    private String insano;
    private String inmonth;
    private String inweeks;
    private String inmonthcp;
    private String inweekscp;

    private Integer decision2;
    private Integer decision1;
    private Integer decision3;
    private Integer decision4;

}
