package com.dae.kdmes.DTO.App02;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Index10Dto {
    private String custcd;
    private String spjangcd;
    private String plan_no;
    private String pcode;
    private String wodv;
    private String wdndv;
    private String wrmc;
    private String wono;
    private String lotno;
    private String line;
    private String opcod;
    private String cltcd;
    private String wocs;
    private String wram;
    private String woam;
    private String prod_sdate;
    private String prod_edate;
    private String prod_qty;
    private String prod_dqty;
    private String qcdate;
    private String qcqty;
    private String end_qty;
    private String ordtype;
    private String orddate;
    private String ordnum;
    private String ordseq;
    private String ordqty;
    private String ord_edate;
    private String outtm;
    private String close_date;
    private String close_perid;
    private String decision;
    private String cls_flag;
    private String work_flag;
    private String dem_flag;
    private String qc_flag;
    private String close_flag;
    private String end_flag;
    private String istore;
    private String ostore;
    private String rwflag;
    private String perid;
    private String remark;
    private Integer workdv;
    private String wflag;
    private String wseq;
    private String tordqty;
    private String qcgb;
    private String demdate;
    private String demnum;
    private String selps;
    private String selck;
    private String batchdv;
    private String ocls_flag;
    private String autodv;
    private String fdate;
    private String tdate;
    private String indate;
    private String inperid;
    private String jpum;
    private String jgugek;
    private String jchajong;
    private String jsayang;
    private String jgugek2;
    private String jpumcode;
    private String jdanwy;
    private String j_sr;
    private String Jpb_gubn;
    private String Jmodel_code;
}
